/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AutobusDirezione {
    'colore': string;
    'intestazione': string;
    'numero': string;
    'returnLink': string;
  }
  interface AutobusDirezioneAttributes extends StencilHTMLAttributes {
    'colore'?: string;
    'intestazione'?: string;
    'numero'?: string;
    'returnLink'?: string;
  }

  interface BusElement {
    'color': string;
    'href': string;
    'identificatore': number;
    'text': string;
  }
  interface BusElementAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'href'?: string;
    'identificatore'?: number;
    'text'?: string;
  }

  interface IntestazioneTabella {
    'color': string;
    'intestazione': string;
    'linea': string;
    'link': string;
  }
  interface IntestazioneTabellaAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'intestazione'?: string;
    'linea'?: string;
    'link'?: string;
  }

  interface PaginaOrari {
    'citta': string;
    'colore': string;
    'intestazione': string;
    'link': string;
    'numero': string;
  }
  interface PaginaOrariAttributes extends StencilHTMLAttributes {
    'citta'?: string;
    'colore'?: string;
    'intestazione'?: string;
    'link'?: string;
    'numero'?: string;
  }

  interface ProjectHome {}
  interface ProjectHomeAttributes extends StencilHTMLAttributes {}

  interface TabellaOrari {
    'citta': string;
    'numero': string;
  }
  interface TabellaOrariAttributes extends StencilHTMLAttributes {
    'citta'?: string;
    'numero'?: string;
  }

  interface VisualizationGrid {
    'transportType': string;
  }
  interface VisualizationGridAttributes extends StencilHTMLAttributes {
    'transportType'?: string;
  }

  interface VisualizationList {
    'transportType': string;
  }
  interface VisualizationListAttributes extends StencilHTMLAttributes {
    'transportType'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'AutobusDirezione': Components.AutobusDirezione;
    'BusElement': Components.BusElement;
    'IntestazioneTabella': Components.IntestazioneTabella;
    'PaginaOrari': Components.PaginaOrari;
    'ProjectHome': Components.ProjectHome;
    'TabellaOrari': Components.TabellaOrari;
    'VisualizationGrid': Components.VisualizationGrid;
    'VisualizationList': Components.VisualizationList;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'autobus-direzione': Components.AutobusDirezioneAttributes;
    'bus-element': Components.BusElementAttributes;
    'intestazione-tabella': Components.IntestazioneTabellaAttributes;
    'pagina-orari': Components.PaginaOrariAttributes;
    'project-home': Components.ProjectHomeAttributes;
    'tabella-orari': Components.TabellaOrariAttributes;
    'visualization-grid': Components.VisualizationGridAttributes;
    'visualization-list': Components.VisualizationListAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAutobusDirezioneElement extends Components.AutobusDirezione, HTMLStencilElement {}
  var HTMLAutobusDirezioneElement: {
    prototype: HTMLAutobusDirezioneElement;
    new (): HTMLAutobusDirezioneElement;
  };

  interface HTMLBusElementElement extends Components.BusElement, HTMLStencilElement {}
  var HTMLBusElementElement: {
    prototype: HTMLBusElementElement;
    new (): HTMLBusElementElement;
  };

  interface HTMLIntestazioneTabellaElement extends Components.IntestazioneTabella, HTMLStencilElement {}
  var HTMLIntestazioneTabellaElement: {
    prototype: HTMLIntestazioneTabellaElement;
    new (): HTMLIntestazioneTabellaElement;
  };

  interface HTMLPaginaOrariElement extends Components.PaginaOrari, HTMLStencilElement {}
  var HTMLPaginaOrariElement: {
    prototype: HTMLPaginaOrariElement;
    new (): HTMLPaginaOrariElement;
  };

  interface HTMLProjectHomeElement extends Components.ProjectHome, HTMLStencilElement {}
  var HTMLProjectHomeElement: {
    prototype: HTMLProjectHomeElement;
    new (): HTMLProjectHomeElement;
  };

  interface HTMLTabellaOrariElement extends Components.TabellaOrari, HTMLStencilElement {}
  var HTMLTabellaOrariElement: {
    prototype: HTMLTabellaOrariElement;
    new (): HTMLTabellaOrariElement;
  };

  interface HTMLVisualizationGridElement extends Components.VisualizationGrid, HTMLStencilElement {}
  var HTMLVisualizationGridElement: {
    prototype: HTMLVisualizationGridElement;
    new (): HTMLVisualizationGridElement;
  };

  interface HTMLVisualizationListElement extends Components.VisualizationList, HTMLStencilElement {}
  var HTMLVisualizationListElement: {
    prototype: HTMLVisualizationListElement;
    new (): HTMLVisualizationListElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'autobus-direzione': HTMLAutobusDirezioneElement
    'bus-element': HTMLBusElementElement
    'intestazione-tabella': HTMLIntestazioneTabellaElement
    'pagina-orari': HTMLPaginaOrariElement
    'project-home': HTMLProjectHomeElement
    'tabella-orari': HTMLTabellaOrariElement
    'visualization-grid': HTMLVisualizationGridElement
    'visualization-list': HTMLVisualizationListElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'autobus-direzione': HTMLAutobusDirezioneElement;
    'bus-element': HTMLBusElementElement;
    'intestazione-tabella': HTMLIntestazioneTabellaElement;
    'pagina-orari': HTMLPaginaOrariElement;
    'project-home': HTMLProjectHomeElement;
    'tabella-orari': HTMLTabellaOrariElement;
    'visualization-grid': HTMLVisualizationGridElement;
    'visualization-list': HTMLVisualizationListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
